Benchmark
jbapple/crate-dictionary pull request #1
Opened 2021-12-10 21:40 UTC by gabriel-domingues

These are the added changes to the benchmark plus some code changes for improving efficiency. There is still work needed to be done on FindLongest.

2021-12-11 18:38 UTC, jbapple requested changes
Thank you for this patch! I see you made some idiomatic changes and also reduces some calls to PDEP and TZCNT.

2021-12-11 18:38 UTC, jbapple commented on Makefile
> +-Wno-unused-variable -Wno-unused-function -march=skylake -O3 \
Without skylake-avx512, we can't do the crate insert and lookup in O(1) worst-case time.

2021-12-11 18:38 UTC, jbapple commented on pd-cache-test.cpp
> +  return static_cast<__uint128_t>(x) *
This is the older way of specifying 128-bit integers and should not be needed past gcc 4.6

2021-12-11 18:38 UTC, jbapple commented on pd-cache-test.cpp
> +      assert(pc_test[rem] == pc_test[rem].Export());
Do you mean pc[rem].Export()?

2021-12-11 18:38 UTC, jbapple commented on pd-cache-test.cpp
> +  vector<pair<uint64_t, uint64_t>> lines(1 << 19);
Why not start with a zero-length vector so we don't accidentally end up reading {0,0}s at the end if the file is short?

2021-12-11 18:38 UTC, jbapple commented on pd-cache.h
> +    for (; occupancy >= 27; --occupancy)
Let's avoid using multi-line loops without brackets.

2021-12-11 18:38 UTC, jbapple commented on pd-cache.h
> +#ifdef NDEBUG
Did you mean #ifndef?

2021-12-11 18:38 UTC, jbapple commented on pd-cache.h
> -  int8_t freelist_front = 0;
I left it signed to more easily debug invalid values.

2021-12-11 18:38 UTC, jbapple commented on pd-cache.h
> +    if (slot != begin)
Here, please make single-line or re-insert brackets.

2021-12-11 18:38 UTC, jbapple commented on pd-cache.h
> +  inline auto FindQuotient(unsigned quotient, unsigned remainder) const
inline inhibits debugability, let's avoid it for now

2021-12-11 18:38 UTC, jbapple commented on pd-cache.h
> +      -> tuple<uint64_t, uint64_t, uint64_t> {
Just put this in print of the function and only use auto return types when the return type explicitly mentions one of the parameters.

2021-12-11 18:38 UTC, jbapple commented on pd-cache.h
> +          return a.fingerprint == remainder;
This code is more complex than the previous for loop.

2021-12-11 18:38 UTC, jbapple commented on pd-cache.h
> +  uint64_t MakeRoom(unsigned quotient) {
Making this unsigned silently cases accidentally-negative begin_data into less debuggable large 64-bit integers. Is there a performance benefit?

2021-12-11 18:38 UTC, jbapple commented on pd-cache.h
> -     memmove(&data[begin_data + 1], &data[begin_data],
Why remove the memmove?

2021-12-11 18:38 UTC, jbapple commented on pd-cache.h
> -  int CountValues() const {
Why remove? Can be useful for debugging.

2021-12-11 18:38 UTC, jbapple commented on pd-cache.h
> +    rotate(data + (end - 1), data + end, data + 27);
I think rotate is one more copy. I also expect it to be less SIMD-friendly than memmove

2021-12-12 06:00 UTC, gabriel-domingues commented on Makefile
> +-Wno-unused-variable -Wno-unused-function -march=skylake -O3 \
Correct, I had to make this change since my machine is a Coffee Lake, which does not have AVX512. Which AVX512 instructions are we using exactly?

2021-12-12 06:00 UTC, gabriel-domingues commented on pd-cache-test.cpp
> +      assert(pc_test[rem] == pc_test[rem].Export());
Yes, fixed.

2021-12-12 06:00 UTC, gabriel-domingues commented on pd-cache-test.cpp
> +  vector<pair<uint64_t, uint64_t>> lines(1 << 19);
I changed this to a reserve.

2021-12-12 16:33 UTC, jbapple requested changes
Looks good! One or two more comments left.

2021-12-12 16:33 UTC, jbapple commented on Makefile
> +-Wno-unused-variable -Wno-unused-function -march=skylake -O3 \
See pd512.h. We could use -march=native for now.

2021-12-14 01:24 UTC, jbapple requested changes

2021-12-14 01:24 UTC, jbapple commented on Makefile
> +-std=c++17 -I../../c++/util -mavx2 -fno-strict-aliasing -fno-exceptions -DNDEBUG # -ggdb3 -fsanitize=address
Now that we have -march=native, you can remove -mavx2

2021-12-14 01:24 UTC, jbapple commented on pd-cache.h
> +    rotate(data + begin, slot, slot + 1);
Why rotate - why not memmove? See previous comments on this PR.

2021-12-14 01:24 UTC, jbapple commented on pd-cache.h
> +    // Approximate finder for longest
Let's make that a separate PR, please.

2021-12-14 01:24 UTC, jbapple commented on pd-cache-test.cpp
> +      assert(pc_test[rem] == pc[rem].Export());
Have you run with this assert on?

2021-12-14 10:27 UTC, gabriel-domingues commented on pd-cache.h
> +    rotate(data + begin, slot, slot + 1);
This implements the LRU behavior of moving the most recently accessed value to the front. Now, this is exactly what (the left) rotate does - it moves the value of the middle (i.e. slot) to the front in a circular fashion. There is no extra move, which was what the temporary variable did. Also, the previous code had an extra shift of the data (from begin to end not just until the slot), copying the reference to the slot, which we only needed once and at the front.

2021-12-18 19:41 UTC, jbapple requested changes
This PR has grown quite complex. Can you close it and send smaller PRs, each of which doing one single thing, like "changing whitespace" or "optimizing memmove calls" or "optimizing select64 calls"?

2021-12-19 14:17 UTC, closed without merging