All changes related to: Benchmarks
jbapple/crate-dictionary pull request #6
Opened 2021-12-21 17:19 UTC by gabriel-domingues

2021-12-21 17:31 UTC, jbapple requested changes

2021-12-21 17:31 UTC, jbapple commented on Makefile
> +-march=native -O3  -std=c++17 -I../../c++/util -fno-exceptions \
Does -fno-exceptions make this benchmark faster on your machine?

2021-12-21 17:31 UTC, jbapple commented on pd-cache-test.cpp
> -      auto e0 = pc_test[hs % many].FindEntry(hs / many);
Why remove this?

2021-12-21 17:31 UTC, jbapple commented on pd-cache-test.cpp
> +    FullLRU pc_lru(many1 * 27);
I don't think this is right anymore, as this normalizes by number of keys, rather than size.

2021-12-21 17:31 UTC, jbapple commented on pd-cache-test.cpp
> -    const auto begin_length = i.LoadInMemory();
Why change this section - aren't we doing basically the same thing now?

2021-12-21 17:38 UTC, gabriel-domingues commented on pd-cache-test.cpp
> -      auto e0 = pc_test[hs % many].FindEntry(hs / many);
We only need to check the condition once per loop, this is the last thing done before `#endif`

2021-12-21 17:41 UTC, gabriel-domingues commented on pd-cache-test.cpp
> -    const auto begin_length = i.LoadInMemory();
I removed all the IO operations out of the benchmark, including printing to the console, so I had to have them all outside. Moreover, I had to add the allocations there and use `std::chrono` to guarantee better measurements.

2021-12-21 17:44 UTC, gabriel-domingues commented on pd-cache-test.cpp
> +    FullLRU pc_lru(many1 * 27);
I agree, but to compare performance it will be more interesting to do as such. I shall change it to by memory after we establish all improvements on speed.

2021-12-21 17:49 UTC, gabriel-domingues commented on Makefile
> +-march=native -O3  -std=c++17 -I../../c++/util -fno-exceptions \
We need to make sure we don't pay for this if we don't use it. In particular, make sure things like standard algorithms on both the implementation and the baseline don't throw. Also, we don't have to write `nothrow` everywhere.

2021-12-24 18:50 UTC, jbapple approved these changes

2021-12-24 18:50 UTC, merged